#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: codecoverage-run
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  tasks:
  - name: clone-framework
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/framework
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "1"
    - name: subdirectory
      value: framework
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-extensions
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/extensions
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "1"
    - name: subdirectory
      value: extensions
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-managers
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/managers
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "1"
    - name: subdirectory
      value: managers
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-obr
    taskRef:
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/obr
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "1"
    - name: subdirectory
      value: obr
    workspaces:
    - name: output
      workspace: git-workspace
  - name: codecoverage
    taskRef: 
      name: codecoverage-run
    runAfter:
    - clone-obr
    - clone-framework
    - clone-extensions
    - clone-managers
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: https://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/obr/
    workspaces:
    - name: git-workspace
      workspace: git-workspace
