#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codecoverage-run
spec:
  params:
  - name: distBranch
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
  steps:
  - name: run-tests
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-cli-ibm-amd64:{{ .Values.cliVersion }}
    imagePullPolicy: Always
    command:
    - galasactl
    - runs
    - submit
#
    - --stream
    - inttests
    - --tag
    - codecoverage
    - --trace
#
    - --bootstrap
    - http://galasa-cicsk8s.hursley.ibm.com/bootstrap
    - --throttle
    - '1' 
    - --throttlefile
    - throttle
    - --poll
    - '10'
    - --progress
    - '1'
#
    - --reportyaml
    - tests.yaml
#
    - --override
    - galasaecosystem.runtime.repository=http://galasadev-cicsk8s.hursley.ibm.com/codecov/maven/obr
    - --override
    - galasaecosystem.docker.version=codecov
    - --override
    - java.jacoco.code.coverage=true
    - --override
    - java.jacoco.save.location=https://nexus.galasa.dev/repository/jacoco/codecov/execs
    - --override
    - java.jacoco.save.credentials=JACOCO
    - --override
    - zos.dse.tag.PRIMARY.imageid=MV2D
    - --override
    - zos.dse.tag.PRIMARY.clusterid=PLEX2
  - name: catresults
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build:{{ .Values.buildImage }}
    command:
    - cat
    - tests.yaml
