#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codecoverage-run
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
#
#
#
  params:
  - name: distBranch
    type: string
  - default: {{ .Values.mavenProxy }}
    name: mavenCentralRepo
    type: string
  - default: {{ .Values.mavenProxy }}
    name: managersSourceRepo
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
#
#
#
  steps:
#
# Get all the sources and classes for all bundles marked for copyright checking in the release.yaml
#
  - name: generate-pom-sources
    image: $(params.dockerRepo)/galasadev/galasa-build:{{ .Values.buildImage }}
    workingDir: /workspace
    command:
    - galasabld
    - template
    - --releaseMetadata
    - /workspace/git/framework/release.yaml
    - --releaseMetadata
    - /workspace/git/extensions/release.yaml
    - --releaseMetadata
    - /workspace/git/managers/release.yaml
    - --releaseMetadata
    - /workspace/git/obr/release.yaml
    - --template
    - /workspace/git/obr/codecoveragetemplates/pomfetch.template
    - --output
    - pom.xml
    - --codecoverage
#
# TEMP - lets see what was templated
#
  - name: cattemplate
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build:{{ .Values.buildImage }}
    command:
    - cat
    - pom.xml
#
# Perform the actual fetch
#
  - name: fetch-maven-artifacts
    image: $(params.dockerRepo)/galasadev/galasa-build
    workingDir: /workspace
    command:
    - mvn
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - --settings
    - pom.xml
    - -B
    - -e
    - -fae
    - process-sources
    resources: {}
#
# TEMP - Make sure target is populated
#
  - name: lstarget
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build:{{ .Values.buildImage }}
    command:
    - ls
    - -l
    - target
#
# Run the codecoverage tests in Galasa
#
  - name: run-tests
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-cli-ibm-amd64:{{ .Values.cliVersion }}
    imagePullPolicy: Always
    command:
    - galasactl
    - runs
    - submit
#
    - --stream
    - inttests
    - --tag
    - codecoverage
    - --trace
#
    - --bootstrap
    - http://galasa-cicsk8s.hursley.ibm.com/bootstrap
    - --throttle
    - '1' 
    - --throttlefile
    - throttle
    - --poll
    - '10'
    - --progress
    - '1'
#
    - --reportyaml
    - tests.yaml
#
    - --override
    - galasaecosystem.runtime.repository=http://galasadev-cicsk8s.hursley.ibm.com/codecov/maven/obr
    - --override
    - galasaecosystem.docker.version=codecov
    - --override
    - java.jacoco.code.coverage=true
    - --override
    - java.jacoco.save.location=https://nexus.galasa.dev/repository/jacoco/codecov/execs
    - --override
    - java.jacoco.save.credentials=JACOCO
    - --override
    - zos.dse.tag.PRIMARY.imageid=MV2D
    - --override
    - zos.dse.tag.PRIMARY.clusterid=PLEX2
#
# TEMP - See the results
#
  - name: catresults
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build:{{ .Values.buildImage }}
    command:
    - cat
    - tests.yaml
