#
# Copyright contributors to the Galasa project 
#
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-build
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","containers","services","persistentvolumeclaims","serviceaccounts","secrets","limitranges"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments","replicasets","statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "v1beta1"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns","pipelineresources","taskruns"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]