#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: clone-kubernetes-operator-
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  pipelineRef:
    name: branch-clone-kubernetes-operator
  params:
  - name: distBranch
    value: "release"
  - name: fromBranch
    value: "main"
#  - name: overwrite
#    value: "--overwrite"
#  - name: force
#    value: ""
