#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: resources-
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
#
#
#
spec:
#
#
#
  pipelineRef:
    name: resources-build
  params:
  - name: distBranch
    value: "release"
#
#
#
  - name: version
    value: "0.0.0"
