#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-javadocs
  labels:
    app: maven-javadocs
spec:
  replicas: {{ .Values.replicas.standard }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: maven-javadocs
  template:
    metadata:
      labels:
        app: maven-javadocs
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: maven-javadocs
        image: {{ .Values.registry }}/galasadev/galasa-maven-javadoc:{{ .Values.branch }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - maven-javadocs
              topologyKey: kubernetes.io/hostname
