#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: galasactl-build
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: clone-cli
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/cli
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: cli
    workspaces:
     - name: output
       workspace: git-workspace
  - name: clone-framework
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/framework
    - name: revision
      value: {{ .Values.branch }}
    - name: refspec
      value: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
    - name: depth
      value: "1"
    - name: subdirectory
      value: framework
    workspaces:
     - name: output
       workspace: git-workspace
  - name: galasactl
    taskRef:
      name: galasactl-build
    runAfter:
    - clone-cli
    - clone-framework
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-deployment
    taskRef:
      name: recycle-deployment
    runAfter:
    - galasactl
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: binary-cli
