#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: galasactl-snapshot
spec:
  resources:
  - name: git-tekton
    type: git
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
  tasks:
  - name: snapshot-cli
    taskRef:
      name: snapshot-generic
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-cli-amd64
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: snapshot-binary
    taskRef:
      name: snapshot-repo
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-cli-binary
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
