#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: galasactl-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: distBranch
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.registry }}
  - name: noPush
    type: string
    default: ""
  steps:
  - name: generate-api
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - java
    - -jar
    - /opt/openapi/openapi-generator-cli.jar
    - generate
    - -i
    - /workspace/git/framework/openapi.yaml
    - -g
    - go 
    - -o
    - pkg/galasaapi
    - --additional-properties=packageName=galasaapi
  - name: clear-mod
    workingDir: /workspace/git/cli/pkg/galasaapi
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - rm
    - -v
    - go.mod
  - name: clear-sum
    workingDir: /workspace/git/cli/pkg/galasaapi
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - rm
    - -v
    - go.sum
  - name: get-commit
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/galasadev/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      sed -i "s/unknowngithash/${COMMIT}/" /workspace/git/cli/pkg/cmd/root.go
      echo commit is $COMMIT
  - name: get-version
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/galasadev/galasa-build
    script: |
      #!/bin/sh
      set +e
      VERSION="$(cat VERSION)"
      sed -i "s/unknowncliversion/${VERSION}/" /workspace/git/cli/pkg/cmd/root.go
      echo version is $VERSION
  - name: galasactl-build
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - make
    - all
  - name: docker-build-cli
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileCli
    - --context=/workspace/git/cli
    - --destination=$(params.dockerRepo)/galasadev/galasa-cli-amd64:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-framework/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=platform=linux-amd64
    - --build-arg=dockerRepository=$(params.dockerRepo)/dockerhub
  - name: docker-build-http
    workingDir: /workspace/git/cli
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileHttp
    - --context=/workspace/git/cli
    - --destination=$(params.dockerRepo)/galasadev/galasa-cli-binary:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-framework/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=branch=$(params.distBranch)
    - --build-arg=dockerRepository=$(params.dockerRepo)/dockerhub
