#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  
  - name: imageName
    type: string
  - name: context
    type: string
  - name: noPush
    type: string
    default: "--no-push"
  - name: dockerfilePath
    type: string
  - name: build-args
    type: array
    default: [""]
  steps:
  - name: docker-build
    workingDir: /workspace/git/
    image: harbor.galasa.dev/common/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /root/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./$(params.dockerfilePath)
    - --context=/workspace/git/$(params.context)
    - --destination=$(params.imageName)
    - --oci-layout-path=/workspace/git/$(params.context)/image-digest
    - --single-snapshot
    - --verbosity=info
    - $(params.noPush)
    - $(params.build-args[*])