#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wrapping-repo-build
#
#
#
spec:
#
#
#
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
#
#
#
  params:
  - name: distBranch
    type: string
  - name: mavenCentralRepo
    type: string
    default: {{ .Values.mavenProxy }}
  - name: mavenSourceRepo
    type: string
    default: {{ .Values.mavenProxy }}
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
#
#
#
  steps:
#
#
#
  - name: gpgdirectory
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - mkdir
    - /workspace/gpg
#
#
#
  - name: import-gpg
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - gpg
    - --homedir
    - /workspace/gpg
    - --pinentry-mode
    - loopback
    - --passphrase-file
    - /root/mavengpg/galasa.passphrase
    - --import
    - /root/mavengpg/galasa.gpg
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg
#
#
#
  - name: copy-settings
    workingDir: /workspace
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - cp
    - /root/mavengpg/settings.xml
    - /workspace/gpg/settings.xml
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg
#
#
#
  - name: wrapping-build
    workingDir: /workspace/git/wrapping
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - mvn
    - -Dgalasa.release.repo=file:/workspace/git/wrapping/docker/repo/
    - -Dgalasa.jacocoEnabled=$(params.jacocoEnabled)
    - -Dgalasa.isRelease=$(params.isRelease)
    - -Dgalasa.source.repo=$(params.mavenSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenSourceRepo)
    - --settings
    - /workspace/gpg/settings.xml
    - -B
    - -e
    - -fae
    - deploy
#
#
#
  - name: get-commit
    workingDir: /workspace/git/wrapping
    image: $(params.dockerRepo)/galasadev/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git/wrapping/docker/wrapping.githash
      echo commit is $COMMIT
#
#
#
  - name: docker-build
    workingDir: /workspace/git/wrapping/docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/wrapping/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-wrapping:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/wrapping/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=branch=$(params.distBranch)    
