#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: security-vulnerability-scanning-
spec:
  params:
  pipelineRef:
    name: secvuln-report
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
      platform: hdc
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-temp