#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: javadoc-build
spec:
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - default: ""
    name: noPush
    type: string
  tasks:
  - name: clone-framework
    params:
    - name: url
      value: https://github.com/galasa-dev/framework
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: framework
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-extensions
    params:
    - name: url
      value: https://github.com/galasa-dev/extensions
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: extensions
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-managers
    params:
    - name: url
      value: https://github.com/galasa-dev/managers
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: managers
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: git-workspace
  - name: clone-obr
    params:
    - name: url
      value: https://github.com/galasa-dev/obr
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: obr
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: git-workspace
  - name: javadoc-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: https://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/managers/
    - name: noPush
      value: $(params.noPush)
    runAfter:
    - clone-obr
    - clone-framework
    - clone-extensions
    - clone-managers
    taskRef:
      kind: Task
      name: javadoc-build
    workspaces:
    - name: git-workspace
      workspace: git-workspace
  - name: recycle-javadoc
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: maven-javadoc
    runAfter:
    - javadoc-build
    taskRef:
      kind: Task
      name: recycle-deployment
    when:
    - input: $(params.noPush)
      operator: notin
      values:
      - --no-push
  - name: recycle-apidoc
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: apidocs
    runAfter:
    - javadoc-build
    taskRef:
      kind: Task
      name: recycle-deployment
    when:
    - input: $(params.noPush)
      operator: notin
      values:
      - --no-push
  workspaces:
  - name: git-workspace
