#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: p2-eclipse
spec:
  type: ClusterIP
  selector:
    app: p2-eclipse
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
