#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: resources-build
#
#
#
spec:
#
#
#
  workspaces:
  - name: git-workspace
#
#
#
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: version
    type: string
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
#
#
#
  tasks:
#
#
#
  - name: clone-docker
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/docker
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "1"
    - name: subdirectory
      value: docker
    workspaces:
     - name: output
       workspace: git-workspace
#
#
#
  - name: build-resources
    taskRef: 
      name: resources-build
    runAfter:
    - clone-docker
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: dockerRepo
      value: $(params.dockerRepo)
