#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: branch-images-delete-galasa
spec:
  params:
  - name: distBranch
    type: string
#
#
#
  tasks:
#
#
#
  - name: delete-image-gradle
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-gradle
#
#
#
  - name: delete-image-maven
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-maven
#
#
#
  - name: delete-image-framework
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-framework
#
#
#
  - name: delete-image-extensions
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-extensions
#
#
#
  - name: delete-image-managers
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-managers
#
#
#
  - name: delete-image-obr
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-obr
#
#
#
  - name: delete-image-javadoc-maven
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-javadoc  
#
#
#
  - name: delete-image-eclipse-maven
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-eclipse
#
#
#
  - name: delete-image-isolated-maven
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-isolated
#
#
#
  - name: delete-image-mvp-maven
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-maven-mvp
#
#
#
  - name: delete-image-boot-ibm
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-ibm-boot-embedded-amd64
#
#
#
  - name: delete-image-boot
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-boot-embedded-amd64
#
#
#
  - name: delete-image-obr-generic
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-obr-generic
#
#
#
  - name: delete-image-javadocs
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-javadocs
#
#
#
  - name: delete-image-isolated
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-isolated
#
#
#
  - name: delete-image-mvp
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-mvp
#
#
#
  - name: delete-image-p2
    taskRef: 
      name: delete-branch-image
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: image
      value: galasa-p2
