#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-maven-galasa
spec:
  params:
  - name: version
    type: string
  - name: repository
    type: string
  - name: dockerRepo
    type: string
  steps: 
  - name: deploy-maven
    image: $(params.dockerRepo)/galasadev/galasa-maven-obr:{{ .Values.branch }}
    command:
    - /usr/local/apache2/htdocs/galasabld
    - maven
    - deploy
    - --repository
    - $(params.repository)
    - --local
    - /usr/local/apache2/htdocs
    - --group
    - dev.galasa
    - --version
    - ${params.version}
    - --credentials
    - /workspace/creds/mavencreds.yaml
    volumeMounts:
    - name: maven
      mountPath: /workspace/creds
  volumes:
    - name: mavencreds
      secret:
        secretName: maven-creds
