#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: delete-branch
spec:
  params:
  - name: repo
    type: string
  - name: distBranch
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
#
#
#
  steps: 
#
#
#
  - name: delete-branch
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - galasabld
    - github
    - branch
    - delete
    - --repository
    - $(params.repo)
    - --branch
    - $(params.distBranch)
    - --credentials
    - /workspace/creds/githubcreds.yaml
    volumeMounts:
    - name: githubcreds
      mountPath: /workspace/creds
  volumes:
    - name: githubcreds
      secret:
        secretName: github-creds
