#
# Copyright contributors to the Galasa project 
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recycle-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recycle-deployment
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: galasa-tekton
