#
# Copyright contributors to the Galasa project 
#
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recycle-deployment
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - "deployments/scale"
  - replicasets
  verbs:
  - get
  - list
  - watch
  - patch
