#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidocs
  labels:
    app: apidocs
spec:
  replicas: {{ .Values.replicas.standard }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: apidocs
  template:
    metadata:
      labels:
        app: apidocs
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: apidocs
        image: {{ .Values.registry }}/galasadev/galasa-javadocs:{{ .Values.branch }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - apidocs
              topologyKey: kubernetes.io/hostname
