#
# Copyright contributors to the Galasa project 
# 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kubernetes-operator-build
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: noPush
    type: string
    default: ""
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-galasa-kubernetes-operator
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/galasa-kubernetes-operator
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: galasa-kubernetes-operator
    workspaces:
     - name: output
       workspace: git-workspace
  - name: operator-build-tagged-version
    taskRef:
      name: kubernetes-operator-build
    runAfter:
    - clone-galasa-kubernetes-operator
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
