#
# Copyright contributors to the Galasa project 
#
{{ if eq .Values.endRepositoriesOnly false }}
apiVersion: v1
kind: Service
metadata:
  name: maven-extensions
  labels:
    app: maven-extensions
spec:
  type: ClusterIP
  selector:
    app: maven-extensions
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
{{ end }}