#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: externalise-generic
#
#
#
spec:
#
#
#
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
#
#
#
  params:
#
  - name: distBranch
    type: string
  - name: image
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
  - name: externalDockerRepo
    type: string
#
#
#
  steps: 
#
  - name: snap-generic
    workingDir: /workspace/git/argocd/pipelineFiles/snapshots
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileGeneric
    - --context=/workspace/git/argocd/pipelineFiles/snapshots
    - --destination=$(params.externalDockerRepo)/galasadev/$(params.image):$(params.distBranch)
    - --oci-layout-path=/workspace/git/argocd/pipelineFiles/snapshots/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=image=$(params.image)
    - --build-arg=oldBranch=$(params.distBranch)
