#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snapshot-repo
spec:
  workspaces:
  - name: git-workspace
    mountPath: /workspace/git
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
  - name: image
    type: string
  - name: dockerRepo
    type: string
    default: {{ .Values.dockerRegistry }}
  steps: 
  - name: snap-repo
    workingDir: /workspace/git/argocd/pipelineFiles/snapshots
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileRepo
    - --context=/workspace/git/argocd/pipelineFiles/snapshots
    - --destination=$(params.dockerRepo)/galasadev/$(params.image):$(params.distBranch)
    - --oci-layout-path=/workspace/git/argocd/pipelineFiles/snapshots/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=image=$(params.image)
    - --build-arg=branch=$(params.distBranch)
    - --build-arg=oldBranch=$(params.oldBranch)
