#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: framework-repo-build
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-framework
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/framework
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: framework
    workspaces:
     - name: output
       workspace: git-workspace

  - name: gradle-build
    taskRef:
      name: gradle-build
    runAfter:
    - clone-framework
    params:
    - name: context
      value: framework/galasa-parent
    - name: dockerRepo
      value: harbor-cicsk8s.hursley.ibm.com     
    - name: build-args
      value:   
        - "-PsourceMaven=http://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/maven"
        - "-PcentralMaven=https://artifactory-cicsk8s.hursley.ibm.com/artifactory/maven-proxy/"
        - "-PtargetMaven=/workspace/git/framework/docker/repo"
    workspaces:
     - name: git-workspace
       workspace: git-workspace   

  - name: framework
    taskRef:
      name: framework-repo-build
    runAfter:
    - gradle-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: mavenSourceRepo
      value: http://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/maven
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-deployment
    taskRef:
      name: recycle-deployment
    runAfter:
    - framework
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: maven-framework
