#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catext-repo-build
#
#
#
spec:
#
#
#
  workspaces:
  - name: git-workspace
  - name: github-creds
#
#
#
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: harborRepo
    type: string
    default: {{ .Values.dockerRegistry }}
  - name: mavenCentralRepo
    type: string
    default: {{ .Values.mavenProxy }}
  - name: noPush
    type: string
    default: ""
#
#
#
  tasks:
#########################################################################
### Git Clone                                                         ###
#########################################################################
  - name: clone-catext
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/extended-catalog
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: extended-catalog
    workspaces:
     - name: output
       workspace: git-workspace
     - name: basic-auth
       workspace: github-creds
#########################################################################
### Db2 Build                                                         ###
#########################################################################
  - name: db2-build
    taskRef:
      name: catext-db2-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#########################################################################
### MQ Build                                                          ###
#########################################################################
  - name: mq-build
    taskRef:
      name: catext-mq-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#########################################################################
### CICS Web UI Build                                                 ###
#########################################################################
  - name: cicswebui-build
    taskRef:
      name: catext-cicswebui-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#########################################################################
### Dispatch App                                                      ###
#########################################################################
  - name: dispatch-build
    taskRef:
      name: catext-dispatch-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: mavenCentralRepo
      value: $(params.mavenCentralRepo)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#########################################################################
### API App                                                           ###
#########################################################################
  - name: api-build
    taskRef:
      name: catext-api-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: noPush
      value: $(params.noPush)
    - name: mavenCentralRepo
      value: $(params.mavenCentralRepo)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#########################################################################
### FrontEnd App                                                      ###
#########################################################################
  - name: frontend-build
    taskRef:
      name: catext-frontend-build
    runAfter:
    - clone-catext
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: harborRepo
      value: $(params.harborRepo)
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
