#
# Copyright contributors to the Galasa project 
#
branch: main

currentVersion: 0.20.0

simplatformBranch: prod

managersBranch: prod

cliVersion: prod

mavenRepoBaseImageVersion: 0.16.0

buildImage: latest

dockerRegistry: harbor-cicsk8s.hursley.ibm.com
mavenProxy: https://artifactory-cicsk8s.hursley.ibm.com/artifactory/maven-proxy/
