#
# Copyright contributors to the Galasa project 
#
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: maven-isolated
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  rules:
  - host: galasadev-cicsk8s.hursley.ibm.com
    http:
      paths:
      - backend:
          service:
            name: maven-isolated
            port:
              number: 80
        path: /{{ .Values.branch}}/maven/isolated
        pathType: Prefix
