#
# Copyright contributors to the Galasa project 
#
{{ if eq .Values.endRepositoriesOnly false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecoverage
  labels:
    app: codecoverage
spec:
  replicas: {{ .Values.replicas.standard }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: codecoverage
  template:
    metadata:
      labels:
        app: codecoverage
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: codecoverage
        image: {{ .Values.registry }}/galasadev/galasa-codecoverage:{{ .Values.branch }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - codecoverage
              topologyKey: kubernetes.io/hostname
{{ end }}