#
# Copyright contributors to the Galasa project 
#
{{ if eq .Values.endRepositoriesOnly false }}
apiVersion: v1
kind: Service
metadata:
  name: codecoverage
  labels:
    app: codecoverage
spec:
  type: ClusterIP
  selector:
    app: codecoverage
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
{{ end }}