#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snapshot-galasabld
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
    default: {{ .Values.branch }}
#
#
#
  tasks:
#
#
#
  - name: clone-argocd
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/argocd
    - name: revision
      value: main
    - name: refspec
      value: +refs/heads/main:refs/heads/main
    - name: depth
      value: "1"
    - name: subdirectory
      value: argocd
    workspaces:
     - name: output
       workspace: git-workspace
#
#
#
  - name: snapshot-binary
    taskRef:
      name: snapshot-repo
    runAfter:
    - clone-argocd
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-bld-binary
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#
#
#
  - name: recycle-binary
    taskRef:
      name: recycle-deployment
    runAfter:
    - snapshot-binary
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: binary-bld
#
#
#
  - name: snapshot-bld
    taskRef:
      name: snapshot-generic
    runAfter:
    - clone-argocd
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-bld-amd64
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#
#
#
  - name: snapshot-bld-ibm
    taskRef:
      name: snapshot-generic
    runAfter:
    - clone-argocd
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-bld-ibm-amd64
    workspaces:
     - name: git-workspace
       workspace: git-workspace
#
#
#
  - name: snapshot-buildimage
    taskRef:
      name: snapshot-generic
    runAfter:
    - clone-argocd
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-build
    workspaces:
     - name: git-workspace
       workspace: git-workspace
